enum LocalStorageAction {
  GET = 'GET_LOCAL_STORAGE',
  LOAD_LOCAL_STORAGE = 'LOAD_LOCAL_STORAGE',
  SAVE_LOCAL_STORAGE = 'SAVE_LOCAL_STORAGE',
  REMOVE_LOCAL_STORAGE = 'REMOVE_LOCAL_STORAGE',
}

export default LocalStorageAction;
